import localFont from "next/font/local";
//using google custom fonts
import { Roboto } from "next/font/google"; // Named import for Google fonts
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Corrected Roboto font setup from Google Fonts with named import
const robotoSans = Roboto({
  weight: ["400", "700"], // Define the weights you need
  variable: "--font-roboto-sans",
  subsets: ["latin"], // Choose subsets according to your need
});
const robotoMono = Roboto({
  weight: ["400", "700"],
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        <Navbar />
        <div className="h-screen">{children}</div>
        <footer>this is my footer</footer>
      </body>
    </html>
  );
}
